version: "3.7"
services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: keycloak
    volumes:
      - ./data/import:/opt/keycloak/data/import
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      DB_VENDOR: h2
      APIGEE_API_KEY: ${APIGEE_API_KEY}
      APIGEE_ROLES_ENDPOINT: ${APIGEE_ROLES_ENDPOINT}
  